### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dippa-1** [schilkp/ws2812b_spi#11]
Hi, I've tested this implementation on the nrf52840 and I like it.

I would like to include it in an open source project (https://github.com/mwaylabs/fruitymesh) which is a Bluetooth mesh so I can control many light strips through the mesh.

For me it would be ideal to have a license so I can include the source code directly, maybe with modification with referencing you as the initial creator.

Many thanks

**Comment by schilkp** [comment]
Hi!

Glad to hear your find the code useful, and thank you for pointing out that it is missing a license. Its been some time since I wrote it and I did not realize I never added one. 

I added a MIT license in 95e6edd and am happy for you to use my code. 

All the best,
Philipp

**Comment by dippa-1** [comment]
Thanks for the info. I'm able to control 256 LEDs with SPI but it is not really stable. I assume that there is a problem when BLE packets are received, as their interrupts will have the highest priority and may break the timing of the SPI callback. I used the iterator as I have to send way more than 256 bytes that are supported for sending at once through the SPI chip.
The current idea is to use a secondary small MCU that handles all the low level stuff and only receives color settings from the NRF. That's what we have in most projects in FruityMesh (like one small MCU controlling the motor of a valve and abstracting away most stuff and only providing an API to the Bluetooth MCU).
Would you mind asking him to share the code or i2s settings? Would like to play around with it.
